export const ApiHost = 'http://localhost:3000/api/'
export const LoginEndpoint: string = ApiHost + 'login'
export const RegisterEndpoint: string = ApiHost + 'register'
export const ProductEndpoint: string = ApiHost + 'products'
export const UpdateProductEndpoint: string = ApiHost + 'updateProduct'
export const AddProductEndpoint: string = ApiHost + 'addProduct'
export const DeleteProductEndpoint: string = ApiHost + 'deleteProduct'
export const uploadImageEndpoint: string = ApiHost + 'upload'
export const LoadGalleryEndpoint: string = ApiHost + 'loadGallery'
export const DeleteImageEndpoint: string = ApiHost + 'deleteImage'
export const GetUserDetailsEndpoint: string = ApiHost + 'getUserDetails'
export const GetStoreDetailsEndpoint: string = ApiHost + 'getStoreDetails'
export const UpdateUserDetailsEndpoint: string = ApiHost + 'updateUserDetails'
export const UpdateStoreDetailsEndpoint: string = ApiHost + 'updateStoreDetails'

